services:
  ollama:
    build: ./ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    networks:
      - ai-network

  frontend:
    build: ./frontend
    ports:
      - "4321:4321"
    depends_on:
      - backend
    networks:
      - ai-network

volumes:
  ollama_data:

networks:
  ai-network:
    driver: bridge
